name: Build
on: [push, pull_request]

jobs:
  # Build job. Builds app for Android with Buildozer
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: master

      - name: Set numeric version
        id: settings
        run: echo "::set-output name=numeric_version::$(date +%Y%m%d%H%M%S)"

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          repository_root: master
          workdir: yoga_sequence_app
          buildozer_version: stable
        env:
          BUILDOZER_APP_ANDROID_NUMERIC_VERSION: ${{ steps.settings.outputs.numeric_version }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
